# default: &default
#   adapter: postgresql
#   pool: 5
#   encoding: utf8
#   username: postgres
#   password: postgres
#   host: localhost
#   port: 5433

# development:
#   <<: *default
#   database: cdr-reports

default: &default
  adapter: postgresql
  pool: 5
  encoding: utf8
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: todo_list